feat: complete model of getting family-mart store
kayac-chang/the-overlord-of-beggars pull request #12
Opened 2024-10-22 14:36 UTC by FlandreDaisuki

先做 `GET /stores` 經緯度查詢，keyword 查詢感覺需要討論跟定義一下

![image](https://github.com/user-attachments/assets/190e7c0b-9880-40e2-abed-11e3ede407e1)

2024-10-22 15:01 UTC, kayac-chang commented
@FlandreDaisuki 可以把 `/stores/:store_id/stock` 也做在這支嗎

2024-10-22 15:03 UTC, FlandreDaisuki commented
@kayac-chang 可以啊～但要晚幾天了

2024-10-22 15:04 UTC, kayac-chang commented
> @kayac-chang 可以啊～但要晚幾天了

沒問題～

2024-10-24 16:21 UTC, kayac-chang commented
@FlandreDaisuki 不好意思～
因為考慮到 資料來源 變多，邏輯變複雜。
能否請在 rebase main 之後，按 #13 來整合，謝謝～

2024-10-25 16:30 UTC, kayac-chang requested changes

2024-10-25 16:30 UTC, kayac-chang commented on backend/app/main.py
> +async def get_store_stock(store_id: str = '') -> Response[list[Stock]]:
幫我把 default '' 拿掉好了

2024-10-25 16:30 UTC, kayac-chang commented on backend/app/services/store_search_reducer.py
> +        try:
這邊先不用 try catch

2024-10-25 17:02 UTC, FlandreDaisuki commented on backend/app/main.py
> +async def get_store_stock(store_id: str = '') -> Response[list[Stock]]:
fixed

2024-10-25 17:02 UTC, FlandreDaisuki commented on backend/app/services/store_search_reducer.py
> +        try:
fixed

2024-10-26 06:20 UTC, merged