feat(crawler): parse familymart services
kayac-chang/the-overlord-of-beggars pull request #64
Opened 2024-11-16 05:27 UTC by vn7n24fzkq

For #10 
這邊直接把全家便利商店提供的服務的 raw data 都存下來
裡面包含了冰淇淋的販售種類

再請 @kayac-chang 看一下有沒有問題, 未來要做搜尋功能的時候可以再研究看看這邊應該如何儲存會比較方便業務邏輯那邊搜尋
目前手邊沒有 MySQL 的環境, 可能需要再麻煩測試看看 🙏

2024-11-16 05:42 UTC, kayac-chang requested changes

2024-11-16 05:42 UTC, kayac-chang commented on crawler/family_mart/get_stores_by_city_and_town.py
> +    def get_services(self) -> list[FamilyMartService]:
可以試試用 [field-validators](https://docs.pydantic.dev/latest/concepts/validators/#field-validators) 做前處理，
這樣就不用調用 method。

Example：https://github.com/kayac-chang/the-overlord-of-beggars/blob/41c0072c3093e8adb639fd3e6c8e436da11e77d0/crawler/seven_eleven/models.py#L22

2024-11-16 05:42 UTC, kayac-chang commented on crawler/family_mart/types.py
> +    @classmethod
可以省略這個。

2024-11-16 05:42 UTC, kayac-chang commented on crawler/family_mart/get_stores_by_city_and_town.py
> +        return [
可以試試看這個嗎？[type_adapter](https://docs.pydantic.dev/latest/concepts/type_adapter/)，
如果成功，可以省掉一個 method。

```py
TypeAdapter(list[FamilyMartService]).validate_python(input_str.split(","))
```

2024-11-16 06:57 UTC, vn7n24fzkq commented on crawler/family_mart/get_stores_by_city_and_town.py
> +    def get_services(self) -> list[FamilyMartService]:
這邊原意沒有打算要讓他 parse 再進 db，想說提供一個介面讓後續開發的人可以參考用，因為還沒討論好要怎麼存或是要怎麼做查詢

2024-11-16 07:08 UTC, vn7n24fzkq commented on crawler/family_mart/get_stores_by_city_and_town.py
> +        return [
是可以，不過就是比較限制，外部要呼叫或使用的時候就沒有一個通用的介面，可讀性可能會降低一點 ，各處要自己重寫adapter的邏輯🤔
不過沒問題的話晚一點可以改

2024-11-16 07:10 UTC, vn7n24fzkq commented on crawler/family_mart/types.py
> +    @classmethod
咦，好奇為什麼可以省略，不加的話第一個參數會變成是 self

2024-11-16 07:13 UTC, vn7n24fzkq commented on crawler/family_mart/get_stores_by_city_and_town.py
> +    def get_services(self) -> list[FamilyMartService]:
如果 validator 做處理的話就變成存 enum 那邊的 value 進資料庫，我覺得沒有特別處理的話好像沒什麼意義，因為跟原本基本上一樣，甚至還要自己再補逗號變成字串才好塞 db，除非我們直接存 JSON array的方式

2024-11-16 07:23 UTC, kayac-chang commented on crawler/family_mart/get_stores_by_city_and_town.py
> +        return [
在應用端不會直接調用 crawler 的腳本，crawler 主要是拿來寫入 DB 而已。
應用端根據自身業務，會有自己內部用的 modal，不會跟 crawler 耦合。

2024-11-16 07:24 UTC, kayac-chang commented on crawler/family_mart/types.py
> +    @classmethod
是指整個 classmethod 可以省略。

2024-11-16 15:03 UTC, vn7n24fzkq commented on crawler/family_mart/types.py
> +    @classmethod
OK

2024-11-17 02:11 UTC, vn7n24fzkq commented on crawler/family_mart/get_stores_by_city_and_town.py
> +        return [
修改囉

2024-11-17 02:11 UTC, vn7n24fzkq commented on crawler/family_mart/get_stores_by_city_and_town.py
> +    def get_services(self) -> list[FamilyMartService]:
這邊依照需求改了 再麻煩看一下

2024-11-17 02:14 UTC, vn7n24fzkq commented
Hi, @kayac-chang 
目前改完了, 應該沒什麼問題, 再麻煩看一下
不過不確定 `FAMILY_MART_KEY` 這邊要塞什麼, 所以我還沒測過整個 `init.py`, 可能要環境的人幫忙手動跑看看 `init.py`

2024-11-17 06:01 UTC, kayac-chang commented
> Hi, @kayac-chang 目前改完了, 手動測試過 before validator 應該沒什麼問題, 再麻煩看一下 不過不確定 `FAMILY_MART_KEY` 這邊要塞什麼, 所以我還沒測過整個 `init.py`, 可能要環境的人幫忙手動跑看看 `init.py`

實際運行腳本似乎型別檢查會拋錯，我這邊直接修。

2024-11-17 06:36 UTC, merged